### ISSUE TITLE
php71u-pecl-amqp-1.9.3-2 dependency problem withlibrabbitmq.so on CentOS 7.5

### ISSUE THREAD

**Issue by joernott** [iusrepo/php71u-pecl-amqp#1]
CentOS 7.5/base provides librabbitmq-0.8.0-2 which updates librabbitmq-0.5.2-1 from epel. As librabbitmq-0.5.2-1 is required by php56u-pecl-amqp-1.9.3-1, yum install runs into problems on up-to-date CentOS 7.5 or when updating from CentOS 7.4

**Comment by carlwgeorge** [comment]
Thanks for the heads up. Fixed in 227fb63a5340389f6dab6a0474d391b437020231, and available in ius-testing.
